### ISSUE TITLE
does this work with ember 2.0?

### ISSUE THREAD

**Issue by sma202** [Addepar/ember-table#395]
I get an exception:

File: super-rentals/templates/body-table-container.hbs
Assertion Failed: Using `{{controller}}` or any path based on it ('super-rentals/templates/body-table-container.hbs' @ L4:C6) has been removed in Ember 2.0
Error: Assertion Failed: Using `{{controller}}` or any path based on it ('super-rentals/templates/body-table-container.hbs' @ L4:C6) has been removed in Ember 2.0
    at new Error (native)
    at Error.EmberError (C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:4569:21)
    at assert (C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:1488:13)
    at Object.assert (C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:4339:34)
    at assertPath (C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:11555:22)
    at assertPaths (C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:11550:7)
    at C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:11524:7
    at Walker.visit (C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:18484:7)
    at visitors.ElementNode (C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:18500:16)
    at Walker.children (C:\programming\super-rentals\bower_components\ember\ember-template-compiler.js:18517:7)

**Comment by DanChadwick** [comment]
Try using PR #374. Or there is an Ember 2.0 branch with a commit marked "WIP" which descends from #374, which also switches over the lazy row rendering to an ember-collection. So, no, the master branch does not currently work with 2.0, but work is underway.

**Comment by cyril-sf** [comment]
@sma202 As @DanChadwick mentioned, there is an opened PR ( #374 ) to support Ember >= 1.13.

We are working on finishing it and release it officially.
