### ISSUE TITLE
Cannot read property 'extend' of undefined.

### ISSUE THREAD

**Issue by HaithamMaya** [Addepar/ember-table#445]
I am trying the hello world example (http://opensource.addepar.com/ember-table/#/simple). Getting this stack trace:

```
row-array.js:2 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.callback (row-array.js:2)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:392)
```

**Comment by pzuraq** [comment]
The examples on that website are for Ember Table v1, which is no longer maintained and not compatible with Ember 1.11+. You can get it by installing `ember-table-legacy` if you want, but it's highly recommended that you find a different solution.

**Comment by HaithamMaya** [comment]
@pzuraq I tried following the Github README:

component.hbs
```
    {{#ember-table rows=definedRows columns=definedColumns as |row|}}
      {{#ember-table-row row=row as |cell|}}
        {{cell.value}}
      {{/ember-table-row}}
    {{/ember-table}}
```

component.js
```
definedColumns: [
    {
      columnName: 'Column 1',
      valuePath: 'col1'
    },
    {
      columnName: 'Column 2',
      valuePath: 'col2'
    }
  ],
  definedRows: [
    {
      col1: 'row1',
      col2: 'row1 data'
    },
    {
      col1: 'row2',
      col2: 'row2 data'
    }
  ]
```

And I am on Ember 2.16.2

**Comment by HaithamMaya** [comment]
Just to confirm, I did this on a brand new ember app.

Ember 2.16.2
```
ember new demo-ember-table
ember install ember-table
ember g component sample-table
```

Used the code shown above in the component, and received this error:

```
deprecate.js:115 DEPRECATION: Ember.K is deprecated in favor of defining a function inline. [deprecation id: ember-metal.ember-k] See https://emberjs.com/deprecations/v2.x#toc_code-ember-k-code for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:24138:21)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:24360:9)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:24168:14)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:24360:9)
        at invoke (http://localhost:4200/assets/vendor.js:24372:9)
        at deprecate (http://localhost:4200/assets/vendor.js:24226:24)
        at Object.get (http://localhost:4200/assets/vendor.js:58746:54)
        at Module.callback (http://localhost:4200/assets/vendor.js:86826:38)
        at Module.exports (http://localhost:4200/assets/vendor.js:111:32)
logDeprecationStackTrace @ deprecate.js:115
HANDLERS.(anonymous function) @ handlers.js:14
raiseOnDeprecation @ deprecate.js:127
HANDLERS.(anonymous function) @ handlers.js:14
invoke @ handlers.js:26
deprecate @ deprecate.js:185
get @ index.js:260
(anonymous) @ resize-handler.js:5
Module.exports @ loader.js:106
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
requireModule @ loader.js:27
_extractDefaultExport @ index.js:392
resolveOther @ index.js:113
superWrapper @ ember-utils.js:437
resolve @ resolver.js:144
resolve @ container.js:852
resolve @ container.js:542
resolve @ container.js:546
factoryFor @ container.js:95
factoryFor @ container_proxy.js:40
componentFor @ component_lookup.js:9
lookupComponentPair @ lookup-component.js:41
lookupComponent @ lookup-component.js:66
Environment._this._definitionCache._emberMetal.Cache.name @ environment.js:34
get @ ember-metal.js:2439
getComponentDefinition @ environment.js:144
refineBlockSyntax @ syntax.js:36
compile @ runtime.js:4413
(anonymous) @ runtime.js:4067
compile @ runtime.js:3958
compileStatement @ runtime.js:4716
compileStatements @ runtime.js:4721
compileStatic @ runtime.js:4746
(anonymous) @ runtime.js:845
evaluate @ runtime.js:70
next @ runtime.js:7246
next @ runtime.js:7317
RootState.render @ renderer.js:62
exports.runInTransaction @ ember-metal.js:652
_renderRoots @ renderer.js:341
_renderRootsTransaction @ renderer.js:379
_renderRoot @ renderer.js:299
_appendDefinition @ renderer.js:209
appendOutletView @ renderer.js:192
invoke @ backburner.js:272
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:455
run @ backburner.js:539
join @ backburner.js:546
run.join @ ember-metal.js:4393
(anonymous) @ ember-metal.js:4467
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
deprecate.js:115 DEPRECATION: Ember.K is deprecated in favor of defining a function inline. [deprecation id: ember-metal.ember-k] See https://emberjs.com/deprecations/v2.x#toc_code-ember-k-code for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:24138:21)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:24360:9)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:24168:14)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:24360:9)
        at invoke (http://localhost:4200/assets/vendor.js:24372:9)
        at deprecate (http://localhost:4200/assets/vendor.js:24226:24)
        at Object.get (http://localhost:4200/assets/vendor.js:58746:54)
        at Module.callback (http://localhost:4200/assets/vendor.js:86827:36)
        at Module.exports (http://localhost:4200/assets/vendor.js:111:32)
logDeprecationStackTrace @ deprecate.js:115
HANDLERS.(anonymous function) @ handlers.js:14
raiseOnDeprecation @ deprecate.js:127
HANDLERS.(anonymous function) @ handlers.js:14
invoke @ handlers.js:26
deprecate @ deprecate.js:185
get @ index.js:260
(anonymous) @ resize-handler.js:6
Module.exports @ loader.js:106
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
requireModule @ loader.js:27
_extractDefaultExport @ index.js:392
resolveOther @ index.js:113
superWrapper @ ember-utils.js:437
resolve @ resolver.js:144
resolve @ container.js:852
resolve @ container.js:542
resolve @ container.js:546
factoryFor @ container.js:95
factoryFor @ container_proxy.js:40
componentFor @ component_lookup.js:9
lookupComponentPair @ lookup-component.js:41
lookupComponent @ lookup-component.js:66
Environment._this._definitionCache._emberMetal.Cache.name @ environment.js:34
get @ ember-metal.js:2439
getComponentDefinition @ environment.js:144
refineBlockSyntax @ syntax.js:36
compile @ runtime.js:4413
(anonymous) @ runtime.js:4067
compile @ runtime.js:3958
compileStatement @ runtime.js:4716
compileStatements @ runtime.js:4721
compileStatic @ runtime.js:4746
(anonymous) @ runtime.js:845
evaluate @ runtime.js:70
next @ runtime.js:7246
next @ runtime.js:7317
RootState.render @ renderer.js:62
exports.runInTransaction @ ember-metal.js:652
_renderRoots @ renderer.js:341
_renderRootsTransaction @ renderer.js:379
_renderRoot @ renderer.js:299
_appendDefinition @ renderer.js:209
appendOutletView @ renderer.js:192
invoke @ backburner.js:272
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:455
run @ backburner.js:539
join @ backburner.js:546
run.join @ ember-metal.js:4393
(anonymous) @ ember-metal.js:4467
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
deprecate.js:115 DEPRECATION: Ember.K is deprecated in favor of defining a function inline. [deprecation id: ember-metal.ember-k] See https://emberjs.com/deprecations/v2.x#toc_code-ember-k-code for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:24138:21)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:24360:9)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:24168:14)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:24360:9)
        at invoke (http://localhost:4200/assets/vendor.js:24372:9)
        at deprecate (http://localhost:4200/assets/vendor.js:24226:24)
        at Object.get (http://localhost:4200/assets/vendor.js:58746:54)
        at Module.callback (http://localhost:4200/assets/vendor.js:86828:33)
        at Module.exports (http://localhost:4200/assets/vendor.js:111:32)
logDeprecationStackTrace @ deprecate.js:115
HANDLERS.(anonymous function) @ handlers.js:14
raiseOnDeprecation @ deprecate.js:127
HANDLERS.(anonymous function) @ handlers.js:14
invoke @ handlers.js:26
deprecate @ deprecate.js:185
get @ index.js:260
(anonymous) @ resize-handler.js:7
Module.exports @ loader.js:106
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
Module._reify @ loader.js:143
Module.reify @ loader.js:130
Module.exports @ loader.js:104
requireModule @ loader.js:27
_extractDefaultExport @ index.js:392
resolveOther @ index.js:113
superWrapper @ ember-utils.js:437
resolve @ resolver.js:144
resolve @ container.js:852
resolve @ container.js:542
resolve @ container.js:546
factoryFor @ container.js:95
factoryFor @ container_proxy.js:40
componentFor @ component_lookup.js:9
lookupComponentPair @ lookup-component.js:41
lookupComponent @ lookup-component.js:66
Environment._this._definitionCache._emberMetal.Cache.name @ environment.js:34
get @ ember-metal.js:2439
getComponentDefinition @ environment.js:144
refineBlockSyntax @ syntax.js:36
compile @ runtime.js:4413
(anonymous) @ runtime.js:4067
compile @ runtime.js:3958
compileStatement @ runtime.js:4716
compileStatements @ runtime.js:4721
compileStatic @ runtime.js:4746
(anonymous) @ runtime.js:845
evaluate @ runtime.js:70
next @ runtime.js:7246
next @ runtime.js:7317
RootState.render @ renderer.js:62
exports.runInTransaction @ ember-metal.js:652
_renderRoots @ renderer.js:341
_renderRootsTransaction @ renderer.js:379
_renderRoot @ renderer.js:299
_appendDefinition @ renderer.js:209
appendOutletView @ renderer.js:192
invoke @ backburner.js:272
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:455
run @ backburner.js:539
join @ backburner.js:546
run.join @ ember-metal.js:4393
(anonymous) @ ember-metal.js:4467
mightThrow @ jquery.js:3583
process @ jquery.js:3651
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
jquery.js:3860 jQuery.Deferred exception: Cannot read property 'extend' of undefined TypeError: Cannot read property 'extend' of undefined
    at Module.callback (http://localhost:4200/assets/vendor.js:86729:58)
    at Module.exports (http://localhost:4200/assets/vendor.js:111:32)
    at Module._reify (http://localhost:4200/assets/vendor.js:148:59)
    at Module.reify (http://localhost:4200/assets/vendor.js:135:27)
    at Module.exports (http://localhost:4200/assets/vendor.js:109:10)
    at Module._reify (http://localhost:4200/assets/vendor.js:148:59)
    at Module.reify (http://localhost:4200/assets/vendor.js:135:27)
    at Module.exports (http://localhost:4200/assets/vendor.js:109:10)
    at requireModule (http://localhost:4200/assets/vendor.js:32:18)
    at Class._extractDefaultExport (http://localhost:4200/assets/vendor.js:86085:20) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3860
process @ jquery.js:3655
setTimeout (async)
(anonymous) @ jquery.js:3689
fire @ jquery.js:3317
fireWith @ jquery.js:3447
fire @ jquery.js:3455
fire @ jquery.js:3317
fireWith @ jquery.js:3447
ready @ jquery.js:3920
completed @ jquery.js:3930
row-array.js:2 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.callback (row-array.js:2)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:392)
```

If it helps, I made the defined columns and rows a computed, added a console, and it doesn't print. The errors occur before the computed's are called.

**Comment by pzuraq** [comment]
It looks like you’re installing version 1 still. Version 2 is currently in alpha, so you must install it by manually specifying the version.

**Comment by edwinevans** [comment]
I don't get it. I followed the steps on the site for a new project and got the same error. Since Version 2 is alpha what do you recommend? If you recommend version 2 then what version should I manually specify? Or would you recommend using legacy since I'd prefer something pretty stable and in that case isn't that what the web site should say to do? Thanks!

**Comment by pzuraq** [comment]
Right, that's the unfortunate situation we're in. Ember Table 1 broke when Ember removed ListView, back in 1.12, and there hasn't been a solid occlusion alternative since until Addepar started working with @html-next on VerticalCollection. Ember Table 2 is going to bridge the gap from Ember 1.12 all the way to Ember 3, but doing all of that takes time, and we're working on it.

The site at http://opensource.addepar.com/ is outdated and shows examples for Ember Table 1. We will be taking it down shortly and updating it. For up to date documentation on what is in Master, and what will be coming when ET2 is shipped, you can checkout the README instead.

Ember Table 2 is currently in alpha, meaning it is a very early pre-release. We're hoping to get it stable and in beta soon, but currently we can't make any guarantees about documentation or usability - there may be bugs, the docs may be incomplete, and features may be missing. Until we reach v2.0.0 stable there's a high chance there will be breaking changes in the API, so unless you can update quickly when they happen it's recommended that you hold off until the stable release. We're hoping to get that launched by the end of Q1 as is.

**Comment by edwinevans** [comment]
That completely clears it up. Thank you!

**Comment by edwinevans** [comment]
I'm trying to start the new release off of master branch so I can use this and possibly help out, but I'm getting the following error:

> The "path" argument must be of type string
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:1234:7)
    at Object.keys.map.name (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:124:26)
    at Array.map (<anonymous>)
    at AddonDiscovery.discoverFromDependencies (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:112:70)
    at AddonDiscovery.discoverChildAddons (/usr/local/lib/node_modules/ember-cli/lib/models/addon-discovery.js:76:33)
    at Class.discoverAddons (/usr/local/lib/node_modules/ember-cli/lib/models/addon.js:349:42)
    at Class.initializeAddons (/usr/local/lib/node_modules/ember-cli/lib/models/addon.js:362:10)
    at setupRegistryForEachAddon (/usr/local/lib/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:18:10)
    at Object.module.exports.setupRegistry (/usr/local/lib/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)
An error occurred in the constructor for ember-table at /Users/edwin/MyTemp/experiment/embertable/gitsource/ember-table


I see indeed nodeModulesPath is null in addon-discovery.js. I set NODE_PATH environment variable but that didn't help.

Any recommendations for how I can get started with this? Thanks!

**Comment by edwinevans** [comment]
Note, I just tried hardcoding the nodeModulesPath value in addon-discovery.js and it looks like everything is working! But I'm guessing this isn't the right solution :)
