### ISSUE TITLE
Dummy app does not start

### ISSUE THREAD

**Issue by wuarmin** [Addepar/ember-table#460]
Hello again, 
maybe you can help me. Since I pulled your last commits from master branch, I'm not able to start the dummy app.

The installation fails with:
```
Trace: 
  Error: https://addepar.jfrog.io/addepar/api/npm/npm/@addepar/eslint-config/-/@addepar/eslint-config-1.0.0.tgz: Request failed "401 Unauthorized"
      at ResponseError (/usr/share/yarn/lib/cli.js:163:5)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:59356:26)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.module.exports.Request.onRequestResponse (/usr/share/yarn/lib/cli.js:123971:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at TLSSocket.socketOnData (_http_client.js:363:20)
```
and if I start the server(ember serve), I get following error:
```
Error: Failed to load plugin import: Cannot find module 'eslint-plugin-import'
Referenced from: /home/user/code/ember-table/.eslintrc.js

```
Thank you

**Comment by billy-addepar** [comment]
This is weird since the `@addepar/eslint-config` is published on NPM:

https://www.npmjs.com/package/@addepar/eslint-config

can you try `rm -rf node_modules` and `yarn cache clean`?

**Comment by billy-addepar** [comment]
If that does not work, we will take a look at the permission of `eslint-config` package.

**Comment by pzuraq** [comment]
The yarn lockfile gets updated whenever Addepar devs push, and we use an Artifactory proxy for @addepar packages (and private packages) which messes up the lockfile for everyone else.

You can run `yarn —no-lockfile` to get around this temporarily, we should drop `yarn.lock` from the repo and add it to .gitignore

**Comment by wuarmin** [comment]
@billy-addepar @pzuraq Thank you for the clarification. That solves the issue.
