### ISSUE TITLE
ember install ember-table downloaded ember-table-legacy addon

### ISSUE THREAD

**Issue by BobrImperator** [Addepar/ember-table#518]
### EDIT
related to #445  
and changing version to ``2.0.0-alpha.1`` helped, should be documented though, apparently it won't download the addon for newer versions of ember automatically.
Issue can be closed, thanks ;)

So I encountered the problem after installation, error stack:
```js
jQuery.Deferred exception: Cannot read property 'extend' of undefined TypeError: Cannot read property 'extend' of undefined
    at Module.callback (http://localhost:4200/assets/vendor.js:334849:58)
    at Module.exports (http://localhost:4200/assets/vendor.js:111:32)
    at Module._reify (http://localhost:4200/assets/vendor.js:148:59)
    at Module.reify (http://localhost:4200/assets/vendor.js:135:27)
    at Module.exports (http://localhost:4200/assets/vendor.js:109:10)
    at Module._reify (http://localhost:4200/assets/vendor.js:148:59)
    at Module.reify (http://localhost:4200/assets/vendor.js:135:27)
    at Module.exports (http://localhost:4200/assets/vendor.js:109:10)
    at requireModule (http://localhost:4200/assets/vendor.js:32:18)
    at Class._extractDefaultExport (http://localhost:4200/assets/vendor.js:330663:20) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3818
process @ jquery.js:3606
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
completed @ jquery.js:3888
row-array.js:2 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.callback (row-array.js:2)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:407)
```
I've already suspected something when it installed jquery dependencies via bower, and for testing purposes I've plainly copy pasted an example from README, and encountered error that's above.

So apparently,  using ``ember install ember-table`` downloaded the legacy addon, which uses already non existent ``Ember.ArrayController`` API.
My Ember Version is ``~3.0.0``

That's a conclusion I came to after comparing my ``node_modules/ember-table`` contents with what ``ember-table`` & ``ember-table-legacy`` provides.

That's exactly the file that fails:
```js
// node_modules/ember-table/controllers/row-array.js
import Ember from 'ember';

export default Ember.ArrayController.extend({
  itemController: null,
  content: null,
  lastItem: null,

  rowContent: Ember.computed(function() {
    return [];
  }).property(),

  controllerAt: function(idx, object) {
    var subControllers = this.get('_subControllers');
    var subController = subControllers[idx];
    if (subController) {
      return subController;
    }
    subController = this.get('itemController').create({
      target: this,
      parentController: this.get('parentController') || this,
      content: object
    });
    subControllers[idx] = subController;

    // Keep track of the last row. Because we only use last row status to apply
    // CSS styles, we only need to know which row is the last row when the row
    // is loaded/scrolled into view. At that time, we update the `lastItem`
    // property. This avoids the problem where the last row's data is always
    // loaded (e.g. in the AJAX table). See issue #165.
    if (this._isLastItem(idx)) {
      this.set('lastItem', subController);
    }
    return subController;
  },

  _isLastItem: function(idx) {
    return this.get('content').length - 1 === idx;
  }
});
```
```json
// bower.json
{
  "name": "selleo-dashboard",
  "dependencies": {
    "antiscroll": "git://github.com/Addepar/antiscroll#e0d1538cf4f3fd61c5bedd6168df86d651f125da",
    "jquery-mousewheel": "~3.1.4",
    "jquery-ui": "~1.11.4"
  }
}
// package.json
...
    "ember-table": "^0.9.2",
...
```

How I wanted to use the addon
```hbs
    {{#ember-table as |t|}}
      {{ember-thead api=t columns=columns}}

      {{ember-tbody api=t rows=rows}}

    {{/ember-table}}
```

**Comment by pzuraq** [comment]
Hey @BobrImperator, we're working on publishing a beta soon. When that happens, we'll update the NPM tags to point latest to the beta - in the meantime, it's too unstable to recommend that anyone use the latest library by default.
