### ISSUE TITLE
What's in #master isn't yet fastboot-friendly, due to hammerjs issues.

### ISSUE THREAD

**Issue by lupestro** [Addepar/ember-table#543]
I loaded up #master to take a look ahead. It depends on hammerjs. When I run without fastboot, it comes up with no worries. When I run with Fastboot, I get the following when the app is starting on the fastboot server:

```
C:\Users\rmack\Code\TFS\filterwizard\trunk\source\FilterWizardClient\tmp\broccoli_merge_trees-output_path-aUGdp249.tmp\assets\vendor.js:82419
})(window, document, 'Hammer');
           ^
ReferenceError: document is not defined
    at C:\Users\rmack\Code\TFS\filterwizard\trunk\source\FilterWizardClient\tmp\broccoli_merge_trees-output_path-aUGdp249.tmp\assets\vendor\hammerjs\hammer.js:2643:1
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at VMSandbox.eval (C:\Users\rmack\Code\TFS\filterwizard\trunk\source\FilterWizardClient\node_modules\fastboot\src\vm-sandbox.js:14:16)
``` 
We have not yet placed an `{{ember-table}}` component anywhere in our code -- we start in a day or two after reviewing what we're just finishing up -- so this is probably startup stuff.

**Comment by lupestro** [comment]
Yep. It's the IIFE wrapper. First and last lines, and FastBoot is choking on the last line...
```
/*! Hammer.JS - v2.0.7 - 2016-04-22
 * http://hammerjs.github.io/
 *
 * Copyright (c) 2016 Jorik Tangelder;
 * Licensed under the MIT license */
(function(window, document, exportName, undefined) {
 . . .
})(window, document, 'Hammer');
```
Given what hammerjs does (touch - very document-oriented), there may need to be a way to avoid loading it on a fastboot rendering.
