### ISSUE TITLE
Property set failed: object in path "unwrappedApi" could not be found

### ISSUE THREAD

**Issue by sumeetattree** [Addepar/ember-table#654]
`ember-table: ^2.0.0-beta.4`
`ember-cli: ~3.6.0`
`ember-cli-babel: ^7.1.2`
`ember-source: ~3.6.0`

Sample code:
```js
  // component.js
   ...
   columns: computed(() => [
    { name: 'id', valuePath: 'id' },
    { name: 'name', valuePath: 'name' },
    { name: 'state', valuePath: 'state' },
    { name: 'startedAt', valuePath: 'startedAt' },
    { name: 'endedAt', valuePath: 'endedAt' }
  ]),
  rows: computed(() => [
    {
      "id": 6,
      "name": "Test Game",
      "state": "lost",
      "startedAt": "Wed, 15 Aug 2018 10:01:28 UTC +00:00",
      "endedAt": "Wed, 15 Aug 2018 11:00:00 UTC +00:00",
    },
    {...}
  ]
  ),
```
```hbs
{{!-- template.hbs --}}
<EmberTable as |t|>
  <t.head @columns={{columns}} />
  <t.body @rows={{rows}} />
</EmberTable>
```

Throws:
```js
Error: Property set failed: object in path "unwrappedApi" could not be found.
    at new EmberError (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:46044:23)
    at setPath (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:26818:19)
    at set (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:26761:20)
    at EmberTHead.set (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:37509:29)
    at EmberTHead._updateApi (http://192.168.0.244:4200/engines-dist/admin/assets/engine-vendor-8d69d21e516038cd1bd0fecda30d809d.js:21130:12)
    at new EmberTHead (http://192.168.0.244:4200/engines-dist/admin/assets/engine-vendor-8d69d21e516038cd1bd0fecda30d809d.js:21111:12)
    at Function.create (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:39134:22)
    at Function.superWrapper (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:40048:28)
    at Function.create (http://192.168.0.244:4200/engines-dist/admin/assets/engine-vendor-8d69d21e516038cd1bd0fecda30d809d.js:530:36)
    at Function.superWrapper [as create] (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:40048:28)
    at Function.create (http://192.168.0.244:4200/engines-dist/admin/assets/engine-vendor-8d69d21e516038cd1bd0fecda30d809d.js:728:31)
    at Function.superWrapper [as create] (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:40048:28)
    at FactoryManager.create (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:16036:39)
    at CurlyComponentManager.create (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:20694:37)
    at Object.APPEND_OPCODES.add [as evaluate] (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:54081:29)
    at AppendOpcodes.evaluate (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:53165:27)
    at LowLevelVM.evaluateSyscall (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:55305:28)
    at LowLevelVM.evaluateInner (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:55279:22)
    at LowLevelVM.evaluateOuter (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:55272:22)
    at VM.next (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:56769:28)
    at VM.execute (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:56759:31)
    at TryOpcode.handleException (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:55924:16)
    at UpdatingVMFrame.handleException (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:56047:39)
    at UpdatingVM.throw (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:55871:24)
    at Assert.evaluate (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:53680:25)
    at UpdatingVM.execute (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:55858:24)
    at RenderResult.rerender (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:56062:16)
    at RootState.render (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:21012:44)
    at TransactionRunner.runInTransaction (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:25158:47)
    at InteractiveRenderer._renderRoots (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:21241:90)
    at InteractiveRenderer._renderRootsTransaction (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:21272:22)
    at InteractiveRenderer._revalidate (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:21308:18)
    at invokeWithOnError (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:57809:28)
    at Queue.flush (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:57722:25)
    at DeferredActionQueues.flush (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:57874:31)
    at Backburner._end (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:58304:42)
    at MutationObserver.Backburner._boundAutorunEnd (http://192.168.0.244:4200/assets/vendor-80751bab503ee2f886b81902ff63f8dd.js:58041:22)
```

**Comment by cyk** [comment]
@sumeetattree, could you please try to repro with 2.0.0-beta.7? I think it's fixed in that version.

**Comment by sumeetattree** [comment]
@cyk `2.0.0-beta.7` does not have the same issue. Thank you! Any idea when we could expect it move out of beta?

**Comment by cyril-sf** [comment]
Thanks for reporting the problem, I'm closing this as it's resolved.

We need to fix the Ember 3.x compatibility issues before getting out of beta.
