### ISSUE TITLE
incompatible with embroider

### ISSUE THREAD

**Issue by efx** [Addepar/ember-table#694]
Potentially related to https://github.com/html-next/vertical-collection/issues/260.
In order to get my application to build (which depends on ember-table@2.0.0-beta.7), I needed to use the following exemption:
```js
	return require('@embroider/compat').compatBuild(app, Webpack, {
		staticAddonTrees: true,
		compatAdapters: new Map([
			[
				'ember-table',
				class extends V1Addon {
					customizes(...names) {
						// this causes us to never detect a customized treeForAddon and therefore never run it.
						// the treeForAddon in this package does dubious things, and we end up more correct
						// without it.
						return super.customizes(...names.filter(n => n !== 'treeForAddon'));
					}
				}
			],
			[
				'@html-next/vertical-collection',
				class extends V1Addon {
					customizes(...names) {
						// this causes us to never detect a customized treeForAddon and therefore never run it.
						// the treeForAddon in this package does dubious things, and we end up more correct
						// without it.
						return super.customizes(...names.filter(n => n !== 'treeForAddon'));
					}
				}
			]
		])
	});
```
As a downstream user, I would expect to be able to build my app using embroider as described by their documentation.

**Comment by martony38** [comment]
Using a [fresh repo with ember-table added](https://github.com/martony38/embroider-ember-table-test) build fail with the following error regardless if I update `ember-cli-build` with @efx fix:
```
Build Error (PackagerRunner)

Module build failed (from /Users/lsehabiague/Repos/ember-quickstart/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
deprecate's meta information requires an "id" field.

    at Object.validate (/Users/lsehabiague/Repos/ember-quickstart/node_modules/ember-cli-babel/node_modules/babel-plugin-debug-macros/src/utils/builder.js:161:17)
    at Builder._createMacroExpression (/Users/lsehabiague/Repos/ember-quickstart/node_modules/ember-cli-babel/node_modules/babel-plugin-debug-macros/src/utils/builder.js:94:15)
    at Builder.deprecate (/Users/lsehabiague/Repos/ember-quickstart/node_modules/ember-cli-babel/node_modules/babel-plugin-debug-macros/src/utils/builder.js:148:10)
    at Macros.build (/Users/lsehabiague/Repos/ember-quickstart/node_modules/ember-cli-babel/node_modules/babel-plugin-debug-macros/src/utils/macros.js:53:34)
    at PluginPass.ExpressionStatement (/Users/lsehabiague/Repos/ember-quickstart/node_modules/ember-cli-babel/node_modules/babel-plugin-debug-macros/src/index.js:101:27)
    at newFn (/Users/lsehabiague/Repos/ember-quickstart/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/lsehabiague/Repos/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/lsehabiague/Repos/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/lsehabiague/Repos/ember-quickstart/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/lsehabiague/Repos/ember-quickstart/node_modules/@babel/traverse/lib/context.js:118:16)
```

**Comment by martony38** [comment]
build failing with embroider is caused by `ember-classy-page-object` dependency introduced in https://github.com/Addepar/ember-table/commit/1b94ae144f01716873d8de67aa44ffd90110e09b

**Comment by efx** [comment]
Based on that, I found that you can reproduce it by directly adding [ember-cli-page-object](https://github.com/san650/ember-cli-page-object): https://github.com/efx/ember-table-694
