### ISSUE TITLE
tests breaking with Ember v3.15

### ISSUE THREAD

**Issue by bantic** [Addepar/ember-table#795]
ember 3.15 was released yesterday (Dec 10), and so it is now the "release" version in the build matrix, causing the [build to fail](https://travis-ci.org/Addepar/ember-table/jobs/623723306):

```
not ok 90 Chrome 79.0 - [432 ms] - Integration | footer > basic: renders if footerRows are set
    ---
        actual: >
            null
        stack: >
            Error: Assertion Failed: You attempted to update `rows` on `<(unknown):ember4815>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
            
            `rows` was first used:
            
            - While rendering:
              ----------------
                application
                  index
                    ember-table
                      ember-tfoot
                        this.data-test-row-count
            
            Stack trace for the first usage: 
                at _get2 (http://localhost:7357/assets/vendor.js:34106:11)
                at http://localhost:7357/assets/vendor.js:21218:39
                at runInAutotrackingTransaction (http://localhost:7357/assets/vendor.js:33592:9)
                at track (http://localhost:7357/assets/vendor.js:33899:9)
                at RootPropertyReference.compute (http://localhost:7357/assets/vendor.js:21217:36)
                at RootPropertyReference.value (http://localhost:7357/assets/vendor.js:21104:43)
                at UpdateDynamicAttributeOpcode.evaluate (http://localhost:7357/assets/vendor.js:68329:36)
                at UpdatingVM.execute (http://localhost:7357/assets/vendor.js:71474:16)
            
            Stack trace for the update:
                at notifyPropertyChange (http://localhost:7357/assets/vendor.js:34919:7)
                at _set2 (http://localhost:7357/assets/vendor.js:35465:9)
                at Class.set (http://localhost:7357/assets/vendor.js:47734:29)
                at Class.<anonymous> (http://localhost:7357/assets/vendor.js:172431:25)
                at http://localhost:7357/assets/vendor.js:35976:36
                at untrack (http://localhost:7357/assets/vendor.js:33931:7)
                at ComputedProperty.get (http://localhost:7357/assets/vendor.js:35975:13)
        message: >
            Promise rejected during "renders if footerRows are set": Assertion Failed: You attempted to update `rows` on `<(unknown):ember4815>`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
```

**Comment by llunn** [comment]
Hey.  Not sure if you tracked down a fix or not for this.  Ran into similar problems with two possible solutions posted in the emberjs issue (https://github.com/emberjs/ember.js/issues/18613#issuecomment-569384141)

**Comment by MichalBryxi** [comment]
I created a [minimal reproducible code](https://gitlab.com/michal.bryxi-bugreport/ember-table-bugreport/blob/master/app/templates/users.hbs) that bit me. The problem in my case is that `<EmberTable>` content is filtered based on user input. That input goes to `queryParam`, which has `refreshModel: true`, which will trigger the `model()` hook and that will update `@rows` argument. And then the problem will be that [this line in wrappedRows](https://github.com/Addepar/ember-table/blob/040df201be07fe753ad36a931ce845423d78379a/addon/components/ember-tbody/component.js#L307) will cause the double re-render.

**Comment by MichalBryxi** [comment]
In _my case_ the hack to make it work was:
```hbs
<EmberTable as |t|>
  <t.head @columns={{this.columns}} />
  {{!-- working code: --}}
  <t.body @wrappedRows={{@model}} />

  {{!--
  non working code:
  <t.body @rows={{@model}} />
  --}}
</EmberTable>
```

Please note that this *is* a hack and might not work for you if your code relies on `wrappedRows` functionality. It will also yield following warning explaining that you should not really do this:

```
DEPRECATION: The <frontend@component:ember-tbody::ember491>#wrappedRows computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.
```

**Comment by JamesS-M** [comment]
I don't believe that I'm relying on `wrappedRows` functionality. How would I tell?
I'm calling the table like
```
<EmberTable as |t|>
  ...header
  <t.body @rows={{this.rows}} as |b|>
    <b.row as |r|>
      <r.cell as |cell column|>
        <CellComponent @row={{r}} @cell={{cell}} @column={{column}}/>
      </r.cell>
    </b.row>
  </t.body>
  ...footer
</EmberTable>

**Comment by MichalBryxi** [comment]
I am not sure as I never leaned on that functionality @JamesS-M. From the doc comment for `wrappedRows`: 

> Computed property which updates the CollapseTree and erases caches.

So a table that displays updating tree data? 

The good news is that you can just update `ember-table` now and it should just work.

**Comment by JamesS-M** [comment]
@MichalBryxi Disregard my previous comment. I didn't realize I wasn't on the latest version, which does indeed fix this problem 🤦‍♂
