### ISSUE TITLE
Ember auto import related error getting thrown when installing ember table v4.0.0

### ISSUE THREAD

**Issue by ahemed-haneen** [Addepar/ember-table#959]
ember-cli - v3.28

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: ember-classy-page-object needs to depend on ember-auto-import in order to use ember-cli-page-object
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: ember-classy-page-object needs to depend on ember-auto-import in order to use ember-cli-page-object
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: ember-classy-page-object needs to depend on ember-auto-import in order to use ember-cli-page-object
    at Class.included (/home/developer/Projects/js/test-ember-table-app/node_modules/@embroider/addon-shim/src/index.js:51:27)
    at Class.superWrapper [as included] (/home/developer/Projects/js/test-ember-table-app/node_modules/core-object/lib/assign-properties.js:34:20)
    at /home/developer/Projects/js/test-ember-table-app/node_modules/ember-cli/lib/models/addon.js:497:26
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/home/developer/Projects/js/test-ember-table-app/node_modules/ember-cli/lib/models/addon.js:494:24)
    at Class.included (/home/developer/Projects/js/test-ember-table-app/node_modules/ember-cli/lib/models/addon.js:769:10)
    at Class.superWrapper [as included] (/home/developer/Projects/js/test-ember-table-app/node_modules/core-object/lib/assign-properties.js:34:20)
    at /home/developer/Projects/js/test-ember-table-app/node_modules/ember-cli/lib/models/addon.js:497:26
    at Array.reduce (<anonymous>)
    at Class.eachAddonInvoke (/home/developer/Projects/js/test-ember-table-app/node_modules/ember-cli/lib/models/addon.js:494:24)
```

**Comment by yaxinr** [comment]
temporarily for pnpm add to packege.json
```json
  "pnpm": {
    "overrides": {
      "ember-cli-page-object": "< 1.17.9"
    }
  },
```

**Comment by ahemed-haneen** [comment]
@yaxinr thankyou. i too had a hunch that downgrading to `ember-classy-page-object@^0.7.0` would resolve this issue. but am using yarn(v1 - classic) as package manager so have no clue how to override in yarn

**Comment by yaxinr** [comment]
Yarn resolutions

**Comment by ascudder** [comment]
I opened a PR to try to fix this in the ember-classy-page-object repository, let me know if this helps: https://github.com/Addepar/ember-classy-page-object/pull/38

**Comment by ginomiglio** [comment]
This is specifically an incompatibility with `ember-cli-page-object` >= `v2.0.0-beta.4`. You can add a yarn resolution for `v2.0.0-beta.3` to work around the problem in the cleanest way possible. See https://github.com/Addepar/ember-classy-page-object/issues/39 for details.

**Comment by liberlanco** [comment]
> This is specifically an incompatibility with `ember-cli-page-object` >= `v2.0.0-beta.4`. 

Thank you, that helped. I tried to fix version of `ember-classy-page-object` in dependencies without success, but then just added into dependencies:
```
       "ember-cli-page-object": "v2.0.0-beta.3"
```
and no it works. 
```
node@98e52f465a88:/app/client$ ember -v
ember-cli: 4.1.1
node: 14.20.0

```

**Comment by ginomiglio** [comment]
FYI https://github.com/Addepar/ember-classy-page-object/issues/39 was fixed and released, so if you use `ember-classy-page-object` `v0.8.0-beta.2` this problem should no longer happen. We can probably close this issue now.

**Comment by rreckonerr** [comment]
@ginomiglio Is [this issue](https://github.com/Addepar/ember-table/issues/964) possibly related to ember-cli-page-object/ember-classy-page-object?

**Comment by ginomiglio** [comment]
I'm not sure. I don't think so.
